USERID = 'YOUR_USER_ID'
PASSWORD = 'YOUR_PASSWORD'
MEMORABLE = 'YOUR_MEMORABLE_WORD'
SORT_CODE_AND_ACCOUNT_NUMBER = 'SORT_CODE_DIRECTLY_FOLLOWED_BY_ACCOUNT_NUMBER_WITH_NO_SPACES'
COOKIE_LOCATION = 'A_PATH_THAT_CAN_BE_USED_TO_STORE_A_TEMPORARY_COOKIE'
DOWNLOADED_STATEMENT_LOCATION = 'NOT_CURRENTLY_USED-IGNORE'


